name: qr_code
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  open_file: ^3.0.1
  flutter_pdfview: ^1.2.7
  flutter_swipe_button: ^2.1.3
  get:
  gradient_slide_to_act: ^0.0.2
  sliding_action_button: ^0.0.7
  swipeable_button_view: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # Remove the following lines if not using custom fonts
  # assets:
  #   - assets/fonts/qr_code.ttf  # Font file path
  # fonts:
  #   - family: qr_code  # Custom font name
  #     fonts:
  #       - asset: assets/fonts/qr_code.ttf  # Path to font
